

with tb_wife AS
(
SELECT [MEMBER],
DESCA,
DATE_BIRTH,
ROW_NUMBER() 
OVER(PARTITION BY MEMBER ORDER BY CODE) AS NUMBER 
FROM FILE1_11 WHERE RELATION = 1
)
,
tb_son AS
(
SELECT [MEMBER],
DESCA,
DATE_BIRTH,
ROW_NUMBER() 
OVER(PARTITION BY MEMBER ORDER BY CODE) AS NUMBER 
FROM FILE1_11 WHERE RELATION = 2
)
,
tb_parent AS
(
SELECT [MEMBER],
DESCA,
ROW_NUMBER() 
OVER(PARTITION BY MEMBER ORDER BY CODE) AS NUMBER 
FROM FILE1_11 WHERE RELATION = 3
)
SELECT FILE1_10.CODE AS STR1,
	   FILE1_10.DESCA AS STR2,
	   FILE1_10.DATE_BIRTH AS STR3,
	   FILE1_10.DATE_BEGIN AS STR4,
	   FILE1_10.[JOB_DESCA] AS STR5,
	   FILE1_10.[ADDRESS] AS STR6,
	   FILE1_10.[PHONE] AS STR7,
	   MAX(CASE WHEN tb_Wife.NUMBER = 1 THEN tb_wife.DESCA ELSE NULL END) AS STR8,
	   MAX(CASE WHEN tb_Wife.NUMBER = 1 THEN tb_wife.DESCA ELSE NULL END) AS STR9,
	   MAX(CASE WHEN tb_Wife.NUMBER = 1 THEN tb_wife.DESCA ELSE NULL END) AS STR10,
	   MAX(CASE WHEN tb_Wife.NUMBER = 1 THEN tb_wife.DESCA ELSE NULL END) AS STR11
	   FROM FILE1_10 left join tb_wife on file1_10.CODE = tb_wife.MEMBER
GROUP BY   FILE1_10.CODE,
		   FILE1_10.DESCA,
		   FILE1_10.DATE_BIRTH,
		   FILE1_10.DATE_BEGIN,
		   FILE1_10.[JOB_DESCA],
		   FILE1_10.[ADDRESS],
		   FILE1_10.[PHONE]
