IF 	EXISTS(SELECT 1 FROM 
	sys.indexes where name = 'IX_FILE6_20H_8'
	AND object_id = OBJECT_ID('dbo.FILE6_20H'))
DROP INDEX IX_FILE6_20H_8 ON FILE6_20H


IF 	EXISTS(SELECT 1 FROM sys.columns 
			where name = 'PAYMENT_NO_SAFE'
			AND object_id = OBJECT_ID('dbo.FILE6_20H'))
ALTER TABLE FILE6_20H 
DROP COLUMN PAYMENT_NO_SAFE

ALTER TABLE FILE6_20H 
ADD PAYMENT_NO_SAFE 
AS case when ([TYPE]= 1 OR ([TYPE] = 2 AND years > 1) OR [TYPE]= 7  OR [TYPE]= 9 OR [TYPE] = 11 )  AND NOT [FORM_NO] IS NULL then 1 else 0 end PERSISTED

CREATE INDEX IX_FILE6_20H_8 ON FILE6_20H(PAYMENT_NO_SAFE)
