IF EXISTS
(
	SELECT 1
	From sys.Columns
	WHERE  object_id = OBJECT_ID(N'[dbo].[FILE6_20H]')
	AND NAME = 'PAYMENT_SAVE_MEET'
)
BEGIN

ALTER TABLE [FILE6_20H]
DROP COLUMN PAYMENT_SAVE_MEET 

ALTER TABLE [FILE6_20H]
ADD PAYMENT_SAVE_MEET AS (case when [TYPE]= 2 AND [years] > 1 AND FILE6_20H.FORM_NO IS NOT NULL then 1 else 0 end) PERSISTED
END

GO 

IF  EXISTS
(
	SELECT 1
	From sys.Columns
	WHERE  object_id = OBJECT_ID(N'[dbo].[FILE6_20H]')
	AND NAME = 'PAYMENT_NO_SAFE'
)
BEGIN
ALTER TABLE [FILE6_20H]
DROP COLUMN PAYMENT_NO_SAFE

ALTER TABLE [FILE6_20H]
ADD PAYMENT_NO_SAFE AS (case when ([TYPE]= 1 OR  [TYPE]= 7 OR [TYPE]= 9 OR [TYPE] = 11 ) AND [FORM_NO] IS NOT NULL then 1 else 0 end) PERSISTED 
END
GO


