USE [OLYMPIC]
GO

/****** Object:  StoredProcedure [dbo].[sp_meet_member]    Script Date: 27/09/2024 11:55:17 ã ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[sp_meet_member]
(
@SEASON INT,
@DATE DATETIME,
@DATE1 DATETIME = NULL,
@DATE2 DATETIME =  NULL,
@CODE1 INT = NULL,
@CODE2 INT = NULL,
@DIED BIT = 0,
@SAFE INT = 0
)
AS
BEGIN
WITH tb_paid
AS
(
	SELECT	FILE6_20H.CODE,
			MIN(FILE6_20H.DOC_NO_FLAG) AS DOC_NO
			FROM FILE6_20H
			WHERE (PAYMENT_NO_SAFE = 1 AND FILE6_20H.YEAR_CODE >= @SEASON)
			OR (PAYMENT_SAVE_MEET  = 1 AND FILE6_20H.YEAR_CODE > @SEASON)
			GROUP BY FILE6_20H.CODE
)
SELECT FILE1_10.CODE,
0 AS RELATION,
FILE1_10.DESCA,
FILE6_20H.[DATE],
FILE6_20H.DOC_NO,
FILE6_20H.FORM_NO,
FILE1_10.DATE_BEGIN,
FILE1_10.DATE_BIRTH,
FILE6_20H.TOTAL
FROM FILE1_10 INNER JOIN  FILE6_20H  ON FILE1_10.CODE =  File6_20H.CODE 
INNER JOIN tb_paid ON  FILE6_20H.DOC_NO = SUBSTRING(tb_paid.DOC_NO,13,10)
WHERE FILE1_10.DIED = @DIED
AND (@CODE1 IS NULL OR FILE1_10.CODE >= @CODE1)
AND (@CODE2 IS NULL OR FILE1_10.CODE <= @CODE2)
AND  FILE1_10.DATE_BEGIN <= DATEADD(YEAR,-1,@DATE)
AND (@DATE1 IS NULL OR FILE6_20H.[DATE] >= @DATE1)
AND (@DATE2 IS NULL OR FILE6_20H.[DATE] <= @DATE2)

UNION ALL

SELECT FILE1_10.CODE,
FILE1_11.CODE AS RELATION,
FILE1_11.DESCA,
FILE6_20H.[DATE],
FILE6_20H.DOC_NO,
FILE6_20H.FORM_NO,
FILE1_11.DATE_BEGIN,
FILE1_11.DATE_BIRTH,
FILE6_20H.TOTAL
FROM FILE1_10 INNER JOIN  FILE6_20H  ON FILE1_10.CODE =  File6_20H.CODE 
INNER JOIN tb_paid ON  FILE6_20H.DOC_NO = SUBSTRING(tb_paid.DOC_NO,13,10)
INNER JOIN FILE1_11 ON FILE1_10.CODE = FILE1_11.[MEMBER]
WHERE (@CODE1 IS NULL OR FILE1_10.CODE >= @CODE1)
AND (@CODE2 IS NULL OR FILE1_10.CODE <= @CODE2)
AND  FILE1_11.DATE_BIRTH <= DATEADD(YEAR,-21,@DATE)
AND  FILE1_11.DATE_BEGIN <= DATEADD(YEAR,-1,@DATE)
AND  FILE1_10.DATE_BEGIN <= DATEADD(YEAR,-1,@DATE)
AND (@DATE1 IS NULL OR FILE6_20H.[DATE] >= @DATE1)
AND (@DATE2 IS NULL OR FILE6_20H.[DATE] <= @DATE2)
AND FILE1_11.RELATION =1
END

GO


